---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
platforms:
  - name: molecule-instance-ec2-api-tools-centos
    image: centos:latest
  - name: molecule-instance-ec2-api-tools-ubuntu
    image: ubuntu:latest
provisioner:
  name: ansible
  playbooks:
    create: ../resources/playbooks/docker/create.yml
    prepare: ../resources/playbooks/docker/prepare.yml
    destroy: ../resources/playbooks/docker/destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8